export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL'

export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS'
export const NEW_POST_FAIL = 'NEW_POST_FAIL'

export const GET_POST_COMMENTS_SUCCESS = 'GET_POST_COMMENTS_SUCCESS'
export const GET_POST_COMMENTS_FAIL = 'GET_POST_COMMENTS_FAIL'

export const GET_POST_INFO_SUCCESS = 'GET_POST_INFO_SUCCESS'
export const GET_POST_INFO_FAIL = 'GET_POST_INFO_FAIL'

export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL'

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

